# Generated by Django 6.1.1 on 2026-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='type',
            field=models.CharField(choices=[('deck', 'Deck'), ('collection', 'Collection')], default='deck', max_length=20),
        ),
    ]
