# Generated by Django 6.1.1 on 2026-10-09 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScryfallSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScryfallCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(unique=True)),
                ('oracle_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=10)),
                ('layout', models.CharField(max_length=30)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.scryfallset')),
            ],
        ),
        migrations.CreateModel(
            name='ScryfallCardFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('mana_cost', models.CharField(blank=True, max_length=100)),
                ('type_line', models.CharField(blank=True, max_length=255)),
                ('oracle_text', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('power', models.CharField(blank=True, max_length=10)),
                ('toughness', models.CharField(blank=True, max_length=10)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='cards.scryfallcard')),
            ],
            options={
                'ordering': ['face_index'],
                'constraints': [models.UniqueConstraint(fields=('card', 'face_index'), name='unique_card_face_index')],
            },
        ),
    ]
