# Generated by Django 6.1.1 on 2026-10-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scryfallcard',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='scryfallcard',
            name='released_at',
        ),
        migrations.RemoveField(
            model_name='scryfallcardface',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='scryfallcardface',
            name='power',
        ),
        migrations.RemoveField(
            model_name='scryfallcardface',
            name='toughness',
        ),
        migrations.AddField(
            model_name='scryfallcard',
            name='can_foil',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scryfallcard',
            name='can_nonfoil',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scryfallcard',
            name='collector_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scryfallcard',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scryfallcard',
            name='price_foil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='scryfallcard',
            name='price_nonfoil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
