/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated.collection'
import { Route as AuthenticatedAlbumIndexRouteImport } from './routes/_authenticated.album.index'
import { Route as AuthenticatedAlbumSetCodeRouteImport } from './routes/_authenticated.album.$setCode'
import { Route as AuthenticatedDecksIndexRouteImport } from './routes/_authenticated.decks.index'
import { Route as AuthenticatedDecksDeckIdRouteImport } from './routes/_authenticated.decks.$deckId'
import { Route as AuthenticatedFoldersFolderIdRouteImport } from './routes/_authenticated.folders.$folderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlbumIndexRoute = AuthenticatedAlbumIndexRouteImport.update({
  id: '/album/',
  path: '/album/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlbumSetCodeRoute =
  AuthenticatedAlbumSetCodeRouteImport.update({
    id: '/album/$setCode',
    path: '/album/$setCode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecksIndexRoute = AuthenticatedDecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecksDeckIdRoute =
  AuthenticatedDecksDeckIdRouteImport.update({
    id: '/decks/$deckId',
    path: '/decks/$deckId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFoldersFolderIdRoute =
  AuthenticatedFoldersFolderIdRouteImport.update({
    id: '/folders/$folderId',
    path: '/folders/$folderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/album/$setCode': typeof AuthenticatedAlbumSetCodeRoute
  '/decks/$deckId': typeof AuthenticatedDecksDeckIdRoute
  '/folders/$folderId': typeof AuthenticatedFoldersFolderIdRoute
  '/album/': typeof AuthenticatedAlbumIndexRoute
  '/decks/': typeof AuthenticatedDecksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/album/$setCode': typeof AuthenticatedAlbumSetCodeRoute
  '/decks/$deckId': typeof AuthenticatedDecksDeckIdRoute
  '/folders/$folderId': typeof AuthenticatedFoldersFolderIdRoute
  '/album': typeof AuthenticatedAlbumIndexRoute
  '/decks': typeof AuthenticatedDecksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/collection': typeof AuthenticatedCollectionRoute
  '/_authenticated/album/$setCode': typeof AuthenticatedAlbumSetCodeRoute
  '/_authenticated/decks/$deckId': typeof AuthenticatedDecksDeckIdRoute
  '/_authenticated/folders/$folderId': typeof AuthenticatedFoldersFolderIdRoute
  '/_authenticated/album/': typeof AuthenticatedAlbumIndexRoute
  '/_authenticated/decks/': typeof AuthenticatedDecksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/collection'
    | '/album/$setCode'
    | '/decks/$deckId'
    | '/folders/$folderId'
    | '/album/'
    | '/decks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/collection'
    | '/album/$setCode'
    | '/decks/$deckId'
    | '/folders/$folderId'
    | '/album'
    | '/decks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/collection'
    | '/_authenticated/album/$setCode'
    | '/_authenticated/decks/$deckId'
    | '/_authenticated/folders/$folderId'
    | '/_authenticated/album/'
    | '/_authenticated/decks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/album/': {
      id: '/_authenticated/album/'
      path: '/album'
      fullPath: '/album/'
      preLoaderRoute: typeof AuthenticatedAlbumIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/album/$setCode': {
      id: '/_authenticated/album/$setCode'
      path: '/album/$setCode'
      fullPath: '/album/$setCode'
      preLoaderRoute: typeof AuthenticatedAlbumSetCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decks/': {
      id: '/_authenticated/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof AuthenticatedDecksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decks/$deckId': {
      id: '/_authenticated/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof AuthenticatedDecksDeckIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/folders/$folderId': {
      id: '/_authenticated/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof AuthenticatedFoldersFolderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRoute
  AuthenticatedAlbumSetCodeRoute: typeof AuthenticatedAlbumSetCodeRoute
  AuthenticatedDecksDeckIdRoute: typeof AuthenticatedDecksDeckIdRoute
  AuthenticatedFoldersFolderIdRoute: typeof AuthenticatedFoldersFolderIdRoute
  AuthenticatedAlbumIndexRoute: typeof AuthenticatedAlbumIndexRoute
  AuthenticatedDecksIndexRoute: typeof AuthenticatedDecksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCollectionRoute: AuthenticatedCollectionRoute,
  AuthenticatedAlbumSetCodeRoute: AuthenticatedAlbumSetCodeRoute,
  AuthenticatedDecksDeckIdRoute: AuthenticatedDecksDeckIdRoute,
  AuthenticatedFoldersFolderIdRoute: AuthenticatedFoldersFolderIdRoute,
  AuthenticatedAlbumIndexRoute: AuthenticatedAlbumIndexRoute,
  AuthenticatedDecksIndexRoute: AuthenticatedDecksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
